# Generated by Django 3.1.7 on 2021-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('currently_temperature', models.FloatField()),
                ('daily_temperature_max', models.FloatField()),
                ('daily_temperature_min', models.FloatField()),
                ('weekly_temperature_max', models.FloatField()),
                ('weekly_temperature_min', models.FloatField()),
            ],
        ),
    ]
